{% set name = "jupyterview" %}
# This needs to be updated manually => otherwise the source file won't be found
{% set version = "0.3.1.dev1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # You need to generate the source archive with `python setup.py sdist`
  # before running this recipe
  url: ../dist/{{ name }}-{{ version }}.tar.gz
  
build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python >=3.4
    - setuptools
    - ipywidgets >=7.5,<8
  run:
    - python >=3.4
    - jupyterlab >=2.0.0

test:
  imports:
    - jupyterview

about:
  home: https://github.com/trungleduc/jupyterview
  summary: "Data visualization widget for JupyterLab"
  description: >
    "# JupyterView

    Data visualization widget for JupyterLab."
  keywords: "Jupyter, Widgets, VTK"
  license: BSD

