name: Build

on:
  push:
    branches: master
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"

      - name: Setup pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-3.9-${{ hashFiles('package.json') }}
          restore-keys: |
            pip-3.9-
            pip-
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools codecov flake8 jupyterlab~=3.3 check-manifest
          npm install -g codecov
          npm install -g yarn
      - name: Test the extension
        run: |
          export NODE_OPTIONS=--max_old_space_size=8000
          python -m pip install --upgrade -v .
          jupyter labextension list 2>&1 | grep -ie "jupyterview.*OK"
          check-manifest -v